version: '3.8'

services:
  app:
    container_name: netflix-demo-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - TMDB_API_KEY=${TMDB_API_KEY}
    networks:
      - app-network

networks:
  app-network:
